### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by diaconuliviu85** [se-bastiaan/TorrentStream-Android#19]
Hello

how can I solve this problem? You know anything about it?

`java.lang.NullPointerException
	at rx.fd.TorrentPlayerFragment$1.onClick(TorrentPlayerFragment.java:107)
	at android.view.View.performClick(View.java:4443)
	at android.view.View$PerformClick.run(View.java:18444)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5017)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
	at dalvik.system.NativeStart.main(Native Method)`

**Comment by se-bastiaan** [comment]
This is a question for StackOverflow.
